feat: check if artifact exists locally before attempting download
felixmosh/turborepo-gh-artifacts pull request #12
Opened 2022-09-12 14:06 UTC by AlCalzone

And here's the 3rd part of what we discussed. This PR is based on #11. I can rebase it depending on what we do with #11.

The main point of this PR is to enable other means of persisting the turbo cache between jobs, and avoiding re-downloads when running tasks that re-check the cache for the same hash as previously.

2022-09-12 15:22 UTC, felixmosh commented
I had weird issue, which I thought was related to the version bump, it wasn't.

Can you rebase your code with `master`?

2022-09-12 15:39 UTC, AlCalzone commented
done

2022-09-13 05:59 UTC, felixmosh requested changes

2022-09-13 05:59 UTC, felixmosh commented on src/turboServer.ts
> +      const list = await artifactApi.listArtifacts();
This reverts the caching PR

2022-09-13 07:25 UTC, AlCalzone commented on src/turboServer.ts
> +      const list = await artifactApi.listArtifacts();
oh damn, missed that

2022-09-13 07:26 UTC, AlCalzone commented
fixed

2022-09-13 08:06 UTC, felixmosh approved these changes

2022-09-13 08:06 UTC, merged

2022-09-13 08:06 UTC, felixmosh commented
Thank you for this PR 🙏🏼